name: Ensure RST is well-formed

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rstcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install rstcheck
      - name: Run rstcheck
        run: |
          python -m rstcheck README.rst reference/*.rst
